###
GET http://localhost:8080/ImageViewer_war/ImageViewer?file=jpct.de/river/woman.jpg&ar=true&dither=50

###
GET http://localhost:8080/ImageViewer_war/ImageViewer?file=jpct.de/river/error.jpg&ar=true&dither=50

###
GET http://localhost:8080/ImageViewer_war/ImageViewer?file=jpct.de/river/&ar=true&dither=50
